"""add_warranty_registrations_table

Revision ID: e1b66b561cd0
Revises: 56e70f68e7a7
Create Date: 2026-02-25 16:01:28.888694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1b66b561cd0'
down_revision: Union[str, None] = '56e70f68e7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if warranty_registrations table already exists to avoid duplicate creation
    conn = op.get_bind()
    if not conn.dialect.has_table(conn, 'warranty_registrations'):
        op.create_table('warranty_registrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('warranty_id', sa.Integer(), nullable=True),
        sa.Column('customer_name', sa.String(length=255), nullable=False),
        sa.Column('customer_lastname', sa.String(length=255), nullable=False),
        sa.Column('customer_email', sa.String(length=255), nullable=False),
        sa.Column('customer_phone', sa.String(length=50), nullable=False),
        sa.Column('product_ean13', sa.String(length=13), nullable=False),
        sa.Column('product_name', sa.String(length=500), nullable=True),
        sa.Column('g3_transaction_id', sa.String(length=255), nullable=True),
        sa.Column('g3_pin', sa.String(length=255), nullable=True),
        sa.Column('g3_response', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_code', sa.String(length=50), nullable=True),
        sa.Column('is_test', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_warranty_registrations_g3_transaction_id'), 'warranty_registrations', ['g3_transaction_id'], unique=True)
        op.create_index(op.f('ix_warranty_registrations_id'), 'warranty_registrations', ['id'], unique=False)
        op.create_index(op.f('ix_warranty_registrations_order_id'), 'warranty_registrations', ['order_id'], unique=False)
        op.create_index(op.f('ix_warranty_registrations_product_ean13'), 'warranty_registrations', ['product_ean13'], unique=False)
        op.create_index(op.f('ix_warranty_registrations_status'), 'warranty_registrations', ['status'], unique=False)
    
    op.alter_column('addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_addresses_user_id', table_name='addresses')
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items')
    op.drop_index('ix_cart_items_product_id', table_name='cart_items')
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.alter_column('carts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_carts_user_id', table_name='carts')
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.alter_column('deliveries', 'is_free_delivery',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('deliveries', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_delivery_options_delivery_id', table_name='delivery_options')
    op.alter_column('delivery_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_delivery_translations_delivery_id', table_name='delivery_translations')
    op.alter_column('discount_campaigns', 'target_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_index('idx_orders_payment_status', table_name='orders')
    op.drop_index('idx_orders_session_id', table_name='orders')
    op.drop_index('idx_orders_shipping_status', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.create_index(op.f('ix_orders_shipping_status'), 'orders', ['shipping_status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'processing_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'failed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'refunded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_payments_provider_payment_id', table_name='payments')
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.drop_column('payments', 'webhook_url')
    op.drop_column('payments', 'return_url')
    op.drop_column('payments', 'cancel_url')
    op.drop_index('ix_products_delivery_id', table_name='products')
    op.drop_index('ix_products_ean_unique', table_name='products')
    op.drop_index('ix_products_warranty_id', table_name='products')
    op.drop_constraint('fk_products_delivery_id', 'products', type_='foreignkey')
    op.drop_constraint('fk_products_warranty_id', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'deliveries', ['delivery_id'], ['id'])
    op.create_foreign_key(None, 'products', 'warranties', ['warranty_id'], ['id'])
    op.alter_column('warranties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('warranties', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('warranty_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_warranty_features_warranty_id', table_name='warranty_features')
    op.alter_column('warranty_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_warranty_translations_warranty_id', table_name='warranty_translations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_warranty_translations_warranty_id', 'warranty_translations', ['warranty_id'], unique=False)
    op.alter_column('warranty_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_warranty_features_warranty_id', 'warranty_features', ['warranty_id'], unique=False)
    op.alter_column('warranty_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('warranties', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('warranties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_warranty_id', 'products', 'warranties', ['warranty_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_products_delivery_id', 'products', 'deliveries', ['delivery_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_products_warranty_id', 'products', ['warranty_id'], unique=False)
    op.create_index('ix_products_ean_unique', 'products', ['ean'], unique=True)
    op.create_index('ix_products_delivery_id', 'products', ['delivery_id'], unique=False)
    op.add_column('payments', sa.Column('cancel_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('return_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('webhook_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.create_index('ix_payments_provider_payment_id', 'payments', ['provider_payment_id'], unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.alter_column('payments', 'refunded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'cancelled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'failed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'processing_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_shipping_status', 'orders', ['shipping_status'], unique=False)
    op.create_index('idx_orders_session_id', 'orders', ['session_id'], unique=False)
    op.create_index('idx_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.alter_column('discount_campaigns', 'target_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_delivery_translations_delivery_id', 'delivery_translations', ['delivery_id'], unique=False)
    op.alter_column('delivery_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_delivery_options_delivery_id', 'delivery_options', ['delivery_id'], unique=False)
    op.alter_column('delivery_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deliveries', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('deliveries', 'is_free_delivery',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.create_index('ix_carts_user_id', 'carts', ['user_id'], unique=False)
    op.alter_column('carts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('carts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.create_index('ix_cart_items_product_id', 'cart_items', ['product_id'], unique=False)
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False)
    op.alter_column('cart_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cart_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.create_index('ix_addresses_user_id', 'addresses', ['user_id'], unique=False)
    op.alter_column('addresses', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('addresses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_warranty_registrations_status'), table_name='warranty_registrations')
    op.drop_index(op.f('ix_warranty_registrations_product_ean13'), table_name='warranty_registrations')
    op.drop_index(op.f('ix_warranty_registrations_order_id'), table_name='warranty_registrations')
    op.drop_index(op.f('ix_warranty_registrations_id'), table_name='warranty_registrations')
    op.drop_index(op.f('ix_warranty_registrations_g3_transaction_id'), table_name='warranty_registrations')
    op.drop_table('warranty_registrations')
    # ### end Alembic commands ###
